language: node_js
node_js:
  - node
cache: npm

services:
  - docker

stages:
  - name: run test
    if: type = push

  - name: docker build to docker hub
    if: type = push

jobs:
  include:
    - stage: run test
      script:
        - npm run test
    - stage: docker build to docker hub
      script:
        - bash ./scripts/push-backend-image.sh

before_install:
  - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
    -in travis_rsa.enc -out travis_rsa -d
