version: '3.2'

services:
  backend:
    build: .
    image: patsk135/kookkook-backend
    depends_on:
      - db
    restart: always
    environment:
      DB_URI:
      PORT:
      HOST_IP:
      MQTT_PORT:
      JWT_SECRET:
    ports:
      - 4000:4000

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
