version: '3.2'

services:
  backend:
    image: node:12
    container_name: kookkook-backend-dev
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
    ports:
      - 4000:4000
    environment:
      NODE_ENV: development
      PORT:
      JWT_SECRET:
      LINE_USERID:
      LINE_BOT_TOKEN:
    working_dir: /app
    command: ['npm', 'run', 'start:dev']

  db:
    container_name: kookkook-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
