version: '3.2'

services:
  backend:
    build: .
    image: patsk135/kookkook-backend-dev:latest
    container_name: kookkook-backend-dev
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      PORT: 3000
      JWT_SECRET: jwtsecret
      LINE_USERID: U26da3150bd8eb08e92189daf9ca82e3d
      LINE_BOT_TOKEN: hbuF2G3ORyb6xZsK4ajeUiqPTmFIjNGZqIJr6L9ftCp7gc+dYe0RatFuouYrIi5zGt8uBJX5L6jexP1lLoAtP7Ooa6H/rqtVbOJJaT0vm6JSq0AQ/OHlRMUiV504KApB0tIAVLKxag/4ki5Cmy1gJQdB04t89/1O/w1cDnyilFU=

  db:
    image: postgres
    container_name: kookkook-postgres-dev
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: kookkook-adminer-dev
    restart: always
    ports:
      - 8080:8080
