version: '3.2'

services:
  backend:
    container_name: kookkook-backend-staging
    environment:
      NODE_ENV: staging

  db:
    container_name: kookkook-postgres-staging

  mqtt:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 1883:1883
