version: '3.2'

services:
  backend:
    build: .
    container_name: kookkook-backend
    restart: always
    ports:
      - 4000:4000
    environment:
      NODE_ENV: development

  db:
    image: postgres
    container_name: kookkook-postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: kookkook-adminer-dev
    restart: always
    ports:
      - 8080:8080
