version: '3.2'

services:
  backend:
    image: patsk135/kookkook-backend
    restart: always
    volumes:
      - /app/csv
    environment:
      DB_URI:
      QUERY_DB_URI:
      PORT:
      MQTT_BROKER:
      MQTT_PORT:
      JWT_SECRET:
      LINE_USERID:
      LINE_GROUPID:
      LINE_BOT_TOKEN:
      EMAIL_USER:
      EMAIL_PASSWORD:
    ports:
      - 4000:4000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mqtt:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 1883:1883
