version: '3.2'

services:
  backend:
    image: node:12
    depends_on:
      - db
    container_name: kookkook-backend-dev
    volumes:
      - .:/app
    environment:
      DB_URI: postgres://postgres:password@db/postgres
      QUERY_DB_URI: postgres://user1:password@db/chicken_farm
      NODE_ENV: development
      HOST_IP: mqtt
    working_dir: /app
    command: ['npm', 'run', 'start:dev']

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432

volumes:
  postgres:
